In [19]:
#take the N x 28 x 28 mask np array and create an N x 4 YOLO bounding box based on the mask's dimensions
import numpy as np

def masks_to_yolo_boxes(masks):
    N = masks.shape[0]
    yolo_boxes = np.zeros((N, 4), dtype=np.float32)
    
    for i in range(N):
        mask = masks[i]
        ys, xs = np.where(mask > 0)  # find nonzero pixels
        
        if len(xs) == 0 or len(ys) == 0:
            # No mask -> box is all zeros
            yolo_boxes[i] = [0, 0, 0, 0]
            print("empty box where there shouldn't be")
            continue
        
        xmin, xmax = xs.min(), xs.max()
        ymin, ymax = ys.min(), ys.max()
        
        x_center = (xmin + xmax) / 2.0
        y_center = (ymin + ymax) / 2.0
        width = xmax - xmin
        height = ymax - ymin
        
        # Normalize by the size (28)
        yolo_boxes[i, 0] = x_center / 28.0
        yolo_boxes[i, 1] = y_center / 28.0
        yolo_boxes[i, 2] = width / 28.0
        yolo_boxes[i, 3] = height / 28.0
    
    return yolo_boxes

# Example usage
# yolo_bboxes = masks_to_yolo_bboxes(masks)


In [20]:
for i in range (10, 71, 5): 
    current_mask = np.load('mask/mask_' + str(i) + '.npy')
    yolo_box = masks_to_yolo_boxes(current_mask)
    np.save("yolo_boxes/boxes_" + str(i), yolo_box)
    print(f"Finished with {i}: {yolo_box.shape}")

Finished with 10: (70000, 4)
Finished with 15: (70000, 4)
Finished with 20: (70000, 4)
Finished with 25: (70000, 4)
Finished with 30: (70000, 4)
Finished with 35: (70000, 4)
Finished with 40: (70000, 4)
Finished with 45: (70000, 4)
Finished with 50: (70000, 4)
Finished with 55: (70000, 4)
Finished with 60: (70000, 4)
Finished with 65: (70000, 4)
Finished with 70: (70000, 4)


In [15]:
current_mask = np.load('mask/mask_' + "10" + '.npy')
print(current_mask[2])
print(np.count_nonzero(current_mask[2] == 0))
current_type = np.load("mask/obfuscation_type_10.npy")
print(current_type[0])

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [18]:
for i in range (10, 71, 5): 
    current_mask = np.load('mask/mask_' + str(i) + '.npy')
    zero_counts = np.count_nonzero(current_mask == 0, axis=(1, 2))
    num_full_zero = np.sum(zero_counts == 784)
    print(zero_counts)
    print(f"Number of empty masks in {i} : {num_full_zero}")

[703 706 720 ... 703 706 703]
Number of empty masks in 10 : 0
[671 684 666 ... 666 671 666]
Number of empty masks in 15 : 0
[635 631 635 ... 631 635 635]
Number of empty masks in 20 : 0
[587 588 594 ... 603 588 588]
Number of empty masks in 25 : 0
[559 556 549 ... 549 531 531]
Number of empty masks in 30 : 0
[510 531 510 ... 531 509 509]
Number of empty masks in 35 : 0
[495 467 467 ... 495 480 480]
Number of empty masks in 40 : 0
[460 432 460 ... 434 432 432]
Number of empty masks in 45 : 0
[407 393 393 ... 393 407 407]
Number of empty masks in 50 : 0
[354 392 354 ... 343 343 376]
Number of empty masks in 55 : 0
[343 343 314 ... 343 343 343]
Number of empty masks in 60 : 0
[255 255 313 ... 275 255 275]
Number of empty masks in 65 : 0
[255 235 274 ... 255 235 255]
Number of empty masks in 70 : 0
